### ISSUE TITLE
Drawer component not working

### ISSUE THREAD

**Issue by fbedussi** [swordev/suid#141]
The demo of the Drawer component
https://stackblitz.com/run?file=src%2FApp.tsx

is not working, when I click on a button nothing happens.

When I copy and paste the sample code in my project, I can see the "left", "right", "top", "bottom" buttons, but when I click one of them I get this error:

dev.js:1269 Uncaught TypeError: Cannot use 'in' operator to search for 'Symbol(solid-proxy)' in true
at Object.has (dev.js:1269:15)
at Object.has (dev.js:1236:14)
at Object.has (dev.js:1269:15)
at Object.has (dev.js:1236:14)
at splitProps (dev.js:1303:20)
at Dynamic (dev.js:571:23)
at dev.js:516:12
at untrack (dev.js:421:12)
at Object.fn (dev.js:512:37)
at runComputation (dev.js:694:22)

**Comment by juanrgm** [comment]
Closed via 687898ac4b81c60b4b07c169a2ec090dc68e09e5.
