### ISSUE TITLE
Support for useMediaQuery with SolidStart

### ISSUE THREAD

**Issue by BierDav** [swordev/suid#216]
Currently you get following error when using useMediaQuery with ssr:
```
ReferenceError: window is not defined
    at Module.useMediaQuery [as default] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:12:19)
    at __vite_ssr_exports__.default (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:19:54)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at shared.element.component.element.element [as outlet] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:87:43)
    at get children [as children] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:102:22)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:213:35
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:174:49
    at createMemo (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:83:9)
    at children (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:174:16)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:213:14
    at createMemo (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:83:9)
    at provider (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:209:12)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at children (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:99:46)
    at Show (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:375:68)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at Routes (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:94:32)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at get children [as children] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:48:52)
    at Scaffold (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:16:3)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at get children [as children] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:46:48)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:616:39
    at catchError (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:141:12)
    at get children [as children] (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:616:16)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:213:35
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:174:49
    at createMemo (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:83:9)
    at children (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:174:16)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:213:14
    at createMemo (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:83:9)
    at provider (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:209:12)
    at createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:613:34
    at runWithOwner (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:185:12)
    at runSuspense (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:613:12)
    at Suspense (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:620:15)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at get children [as children] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:41:44)
    at get children [as children] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:32:20)
    at error (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:412:41)
    at catchError (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:141:12)
    at file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:412:12
    at createMemo (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:83:9)
    at ErrorBoundary (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:410:3)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at ErrorBoundary (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:15:32)
    at Proxy.createComponent (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/solid-js/dist/server.js:310:15)
    at get children [as children] (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:39:41)
    at eval (eval at instantiateModule (file:///C:/Users/David%20Bieregger/WebstormProjects/ctonline-solid/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:54396:28), <anonymous>:41:108)
```

**Comment by juanrgm** [comment]
Duplicated (https://github.com/swordev/suid/issues/139).
