### ISSUE TITLE
Hydration error when using `<Select/>`

### ISSUE THREAD

**Issue by BierDav** [swordev/suid#253]
I recently wanted to use the Select component but had to find out that even the simplest form `<Select/>` doesn't work with solid start. When using client only eg. ignore the errors and start editing and look at the live edit results, the error doesn't come up.

Here is a stackblitz, that reproduces the error: https://stackblitz.com/edit/github-bupuae-142ezw

Full error text:

```
TypeError: Cannot read properties of undefined (reading '$component')
    at Object.get (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:398:26)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/@suid/system/Dynamic/Dynamic.jsx:48:83)
    at createServerDynamicComponent (/home/projects/github-bupuae-142ezw/node_modules/@suid/system/Dynamic/Dynamic.jsx:16:16)
    at Dynamic (/home/projects/github-bupuae-142ezw/node_modules/@suid/system/Dynamic/Dynamic.jsx:48:46)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at Select (/home/projects/github-bupuae-142ezw/node_modules/@suid/material/Select/Select.jsx:141:32)
    at Select (/home/projects/github-bupuae-142ezw/node_modules/@suid/system/inspect.js:27:16)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at Home (/home/projects/github-bupuae-142ezw/src/routes/index.tsx:8:32)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at shared.element.component.element.element (/home/projects/github-bupuae-142ezw/node_modules/@solidjs/router/dist/routing.js:87:43)
    at get.children (/home/projects/github-bupuae-142ezw/node_modules/@solidjs/router/dist/components.jsx:102:22)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:280:35)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:241:49)
    at createMemo (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:150:9)
    at children (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:241:16)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:280:14)
    at createMemo (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:150:9)
    at provider (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:276:12)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at children (/home/projects/github-bupuae-142ezw/node_modules/@solidjs/router/dist/components.jsx:99:46)
    at Show (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:442:68)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at Routes (/home/projects/github-bupuae-142ezw/node_modules/@solidjs/router/dist/components.jsx:94:32)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at get.children (/home/projects/github-bupuae-142ezw/src/root.tsx:61:49)
    at get.children (/home/projects/github-bupuae-142ezw/node_modules/@suid/material/styles/ThemeProvider.jsx:13:20)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:280:35)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:241:49)
    at createMemo (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:150:9)
    at children (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:241:16)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:280:14)
    at createMemo (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:150:9)
    at provider (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:276:12)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at ThemeProvider (/home/projects/github-bupuae-142ezw/node_modules/@suid/material/styles/ThemeProvider.jsx:8:32)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at get.children (/home/projects/github-bupuae-142ezw/src/root.tsx:56:48)
    at get.children (/home/projects/github-bupuae-142ezw/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:32:20)
    at error (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:479:41)
    at catchError (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:208:12)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:479:12)
    at createMemo (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:150:9)
    at ErrorBoundary (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:477:3)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at ErrorBoundary (/home/projects/github-bupuae-142ezw/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:15:32)
    at Proxy.createComponent (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:377:15)
    at get.children (/home/projects/github-bupuae-142ezw/src/root.tsx:54:44)
    at eval (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:683:39)
    at catchError (/home/projects/github-bupuae-142ezw/node_modules/solid-js/dist/server.js:208:12)
```

**Comment by juanrgm** [comment]
Duplicated (https://github.com/swordev/suid/issues/139).
